// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hlirmvgytxjvfoorvxsv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhsaXJtdmd5dHhqdmZvb3J2eHN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MzE4MjQsImV4cCI6MjA2MTEwNzgyNH0.RIAMZIvIWbuRyAk6usBMVdh3urYs6WINofL_4RgwK7A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);