// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tifgasqzlnyuvrwqwtjz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpZmdhc3F6bG55dXZyd3F3dGp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzOTA0OTQsImV4cCI6MjA2MTk2NjQ5NH0.IAuaW-pdXj8NERzq7l6BVrt_0ajHthnOOAq3PiImWeM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);